title: project
image:
  back: gray-900
  icon: false
  query: false

tabs:
  content:
    columns:
      - width: 2/3
        sections:
          content:
            type: fields
            fields:
              floatingImage:
                label: Floating image
                type: files
                multiple: false
                required: true
              gallery:
                label: Gallery
                type: files
              description:
                label: Description
                type: textarea
                size: medium
              year:
                label: Year
                type: number
      - width: 1/3
        sections:
          files:
            label: All files
            type: files

  meta: tabs/seo/meta
