title: Site

tabs:
  # Tabs 1 - All pages of the site
  pages_tab:
    label: Content
    icon: page

    columns:
      - width: 1/1

        sections:
          homePage:
            type: pages
            create: false
            label: All pages
            templates:
              - home
              - about
              - legal

  # Tabs 2 - Contact blueprint from plugin
  contact: tabs/seo/contact

  # Tabs 3 - Maintenance toggle field
  maintenance_tab:
    label: Maintenance
    icon: cog

    sections:
      maintenance:
        type: fields
        fields:
          maintenance:
            label: Maintenance
            type: toggle
            text:
              - "no"
              - "yes"
